name: PunishmentManager
version: '${project.version}'
main: org.example.dev.r1nex.punishmentmanager.PunishmentManager
depend: [ LuckPerms ]
api-version: '1.16'
commands:
  ban: {}
  tempban: {}
  unban: {}
  banip: {}
