MySQL:
  dbHost: "db.worldhosts.fun:3306"
  dbName: "s11676_server"
  dbUser: "u11676_RJEMUHzHVz"
  dbPassword: "!@^=IC4AUVDKtIzaD!C6HCTC"

groups:
  - "admin"
  - "tex.admin"
  - "st.sotrudnik"
  - "sotrudnik"
  - "ml.sotrudnik"
  - "stajer"

  # Если игрок/администратор, имеет группу из списка,
  # то игроки не имеющие какую-то группу из списка, не смогут разбанить игрока,
  # который был забанен администратором который наследует группу из списка.


  # И этот список будет работать так-же как и с командами, /ban, /tempban, /banip.
  # То-есть игрока, которого пытаются забанить, если тот наследует группу из этого списка - бан не удастся

Usage:
  banCommand: "&4Неверный синтаксис!\n&cИспользование: &d/<command> {ИГРОК} {ПРИЧИНА}"
  unbanCommand: "&4Неверный синтаксис!\n&cИспользование: &d/<command> {ИГРОК}"
  banipCommand: "&4Неверный синтаксис!\n&cИспользование: &d/<command> {ИГРОК} {ПРИЧИНА}"
  tempbanCommand: "&4Неверный синтаксис!\n&cИспользование: &d/<command> {ИГРОК} {ВРЕМЯ(d/h/m/s)} {ПРИЧИНА}"

Messages: # Default messages
  unban-own: "&6На данном аккаунте бан от команды проекта который запрещено снимать!"
  ban-own: "&6Вы не можете забанить администратора."
  notPerms: "&6У Вас нет прав."
  isBanned: "&4Этот игрок уже забанен."
  notBanned: "&4Этот игрок не забанен."
  defaultReason: "Административный бан!"
  notPlayingPlayer: "&6Этот игрок ни разу не заходил на сервер."
  expireEmpty: "&7<Истекло>"
  formatDate: "&6Неверный формат даты."

MessagesChat: # Сообщения, которые будут выводится при выполнении команд (/ban, /tempban, /banip, /unban)
  ban: "&6Игрок &6%name% &6был забанен игроком &6%admin%. &6Причина: &6[&4%reason%&6]"
  unban: "&6Игрок %name% &6был разбанен игроком &6%admin%."
  banip: "&6IP-Адрес &6%ip% &6был забанен игроком &6%admin%. &6Причина: &6[&4%reason%&6]"
  tempban: "&6Игрок %name% &6был временно забанен на &6%time% &6игроком %admin%. &6Причина: &6[&4%reason%&6]"

MessagesConnect: # Сообщения, которые будут выводится при подключении к серверу, если игрок забанен.
  ban: "&6Вы забанены этом сервере администратором &6%admin% &6навсегда. Причина: &6[&4%reason%&6]"
  tempban: "&6Вы временно забанены на этом сервере администратором &6%admin% &6До авто-разбана &f%time% &6Причина: &6[&4%reason%&6]"
  banip: "&6Вы забанены по IP-Адресу администратором &6%admin%. &6Причина: &6[&4%reason%&6]"